### ISSUE TITLE
Why wait for query?

### ISSUE THREAD

**Issue by arjunmayilvaganan** [helecloud/athena-step-function#1]
Hey,

Thank you so much for open sourcing this code. Just out of curiosity, I have a question. Why wait for query? Why not run the query as a [`.sync` job state](https://docs.aws.amazon.com/step-functions/latest/dg/connect-athena.html)?

I presume that the `.sync` wasn't supported at the time of writing this?

**Comment by faridnsh** [comment]
Yes. There's no point to use this repo anymore since AWS released Athena integration with Step Functions. This wasn't available back then.

**Comment by arjunmayilvaganan** [comment]
Thank you so much for confirming. Just wanted to make sure I wasn’t aware of any limitations.
